name: Deploy to OVH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Cache Node modules
      uses: actions/cache@v2
      with:
        path: |
          frontend/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies for frontend
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cd /d "%GITHUB_WORKSPACE%\\frontend"
        npm install
      shell: cmd

    - name: Build frontend
      run: |
        cd /d "%GITHUB_WORKSPACE%\\frontend"
        npm run build
      shell: cmd

    # Debug: List build directory contents
    - name: List build directory contents
      run: |
        cd /d "%GITHUB_WORKSPACE%\\frontend"
        dir build
      shell: cmd

    # Deployment with FTP for frontend
    - name: Deploy frontend to OVH
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ fromJSON(secrets.FTP_CREDENTIALS).server }}
        username: ${{ fromJSON(secrets.FTP_CREDENTIALS).username }}
        password: ${{ fromJSON(secrets.FTP_CREDENTIALS).password }}
        local-dir: frontend/build/
        server-dir: /www/  # Changement ici pour déployer à la racine
