name: Deploy to OVH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # Ajout d'une étape pour lister le contenu du répertoire de travail
    - name: List directories in the GitHub workspace
      run: dir "$GITHUB_WORKSPACE"

    # Changement de répertoire avec confirmation
    - name: Change directory to frontend and confirm
      run: |
        cd "$GITHUB_WORKSPACE\frontend"
        echo "Current directory:"
        dir

    - name: Install dependencies
      run: npm install

    # Confirmation que les dépendances sont installées correctement
    - name: List node_modules
      run: |
        cd "$GITHUB_WORKSPACE\frontend"
        dir node_modules

    - name: Build
      run: npm run build

    # Vérification du contenu du dossier build après la construction
    - name: List build directory
      run: |
        cd "$GITHUB_WORKSPACE\frontend"
        dir build

    # Déploiement avec FTP
    - name:
