name: Deploy to OVH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # Debug: List directories in the GitHub workspace to confirm structure
    - name: List directories in the GitHub workspace
      run: dir
      shell: cmd

    - name: Install dependencies for frontend
      run: |
        cd /d "%GITHUB_WORKSPACE%\\frontend"
        npm install
      shell: cmd

    - name: Build frontend
      run: |
        cd /d "%GITHUB_WORKSPACE%\\frontend"
        npm run build
      shell: cmd

    # Debug: List build directory contents
    - name: List build directory contents
      run: |
        cd /d "%GITHUB_WORKSPACE%\\frontend"
        dir build
      shell: cmd

    # Deployment with FTP for frontend
    - name: Deploy frontend to OVH
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ fromJSON(secrets.FTP_CREDENTIALS).server }}
        username: ${{ fromJSON(secrets.FTP_CREDENTIALS).username }}
        password: ${{ fromJSON(secrets.FTP_CREDENTIALS).password }}
        local-dir: frontend/build/
        server-dir: /www/frontend/

    # Deployment with FTP for backend
    - name: Deploy backend to OVH
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ fromJSON(secrets.FTP_CREDENTIALS).server }}
        username: ${{ fromJSON(secrets.FTP_CREDENTIALS).username }}
        password: ${{ fromJSON(secrets.FTP_CREDENTIALS).password }}
        local-dir: backend/
        server-dir: /www/backend/
