name: Deploy to OVH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to OVH
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ fromJSON(secrets.FTP_CREDENTIALS).server }}
        username: ${{ fromJSON(secrets.FTP_CREDENTIALS).username }}
        password: ${{ fromJSON(secrets.FTP_CREDENTIALS).password }}
        local-dir: build/
        server-dir: /www/
