name: Deploy to OVH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # Débogage : Lister les répertoires dans l'espace de travail GitHub pour confirmer la structure
    - name: List directories in the GitHub workspace
      run: dir "$GITHUB_WORKSPACE"

    - name: Install dependencies for frontend
      run: |
        cd "$GITHUB_WORKSPACE\frontend"
        npm install

    - name: Build frontend
      run: |
        cd "$GITHUB_WORKSPACE\frontend"
        npm run build

    # Débogage : Lister le contenu du répertoire build
    - name: List build directory contents
      run: |
        cd "$GITHUB_WORKSPACE\frontend"
        dir build

    # Déploiement via FTP
    - name: Deploy to OVH
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ fromJSON(secrets.FTP_CREDENTIALS).server }}
        username: ${{ fromJSON(secrets.FTP_CREDENTIALS).username }}
        password: ${{ fromJSON(secrets.FTP_CREDENTIALS).password }}
        local-dir: frontend/build/
        server-dir: /www/
